services:
    graviton.cache.listener.etagresponselistener:
        class: "%graviton.cache.listener.etagresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 110

    graviton.cache.listener.ifnonematchresponselistener:
        class: "%graviton.cache.listener.ifnonematchresponselistener.class%"
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 100

    ## public aliases for doctrine cache bundle providers
    graviton.cache.provider.local:
        alias: doctrine_cache.providers.local
        public: true
    graviton.cache.provider.file:
        alias: doctrine_cache.providers.file
        public: true
    graviton.cache.provider.array:
        alias: doctrine_cache.providers.array
        public: true
    graviton.cache.provider.redis:
        alias: doctrine_cache.providers.redis
        public: true

    # services for symfony cache (should replace doctrine cache if possible?)
    graviton.cache.adapter.append:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        arguments:
          - ""
          - 0
          - "%kernel.cache_dir%/symcache_append"
