services:
    graviton.cache.listener.etagresponselistener:
        class: "%graviton.cache.listener.etagresponselistener.class%"
        arguments:
          - '@graviton.cache.repository.etag'
        tags:
          -
            name: kernel.event_listener
            event: kernel.response
            method: onKernelResponse
            priority: 110
          -
            name: kernel.event_listener
            event: kernel.controller
            method: onKernelController

    graviton.cache.listener.ifnonematchresponselistener:
        class: "%graviton.cache.listener.ifnonematchresponselistener.class%"

    ## public aliases for doctrine cache bundle providers
    graviton.cache.provider.local:
        alias: doctrine_cache.providers.local
        public: true
    graviton.cache.provider.array:
        alias: doctrine_cache.providers.array
        public: true
    graviton.cache.provider.redis:
        alias: doctrine_cache.providers.redis
        public: true

    graviton.cache.repository.etag:
      class: "%graviton.cache.repository.etag.class%"
      factory: 'doctrine_mongodb.odm.default_document_manager:getRepository'
      arguments:
        - 'GravitonCacheBundle:Etag'
