language: php
sudo: required
cache:
  directories:
    - $HOME/.composer
services:
  - docker
  - rabbitmq
before_script:
  - free -m
  - php -m
  - php -i
  # disable mongodb connectivity for non integration testing
  - >
      if [ "$PHPUNIT_SUITE" != "integration" ]; then
          export MONGODB_URI=mongodb://does.not.exist.example.org:443
      fi
  # disable xdebug for integration tests
  - >
      if [ "$PHPUNIT_SUITE" != "unit" ]; then
          phpenv config-rm xdebug.ini
      fi
  # spin up local mongodb with the version we need
  - >
      if [ "$PHPUNIT_SUITE" = "integration" ]; then
          docker pull mongo:$MONGODB_VERSION
          docker run -d -p 127.0.0.1:27017:27017 mongo:3.6 --smallfiles
      fi
  # install the module
  - pecl channel-update pecl.php.net
  - sleep 5
  - printf "\n" | pecl install -f mongodb-1.5.3
  # memory_limit
  - echo "memory_limit=3G"  >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - php -i | grep -A 4 mongo
  # install our deps
  - export GENERATOR_SYNTHETIC_FIELDS="int:clientId"
  - composer install --no-interaction --ignore-platform-reqs --no-scripts --profile --apcu-autoloader
php:
  - 7.3
env:
  matrix:
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=integration MONGODB_VERSION=3.6
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=integration MONGODB_VERSION=4
    - COMPOSER_CHECK=true PHPUNIT=false
    - COMPOSER_CHECK=false PHPUNIT=true PHPUNIT_SUITE=unit
script:
  - >
      if [ "$PHPUNIT" = "true" ]; then
          bash prepare-for-tests.sh && \
          if [ "$PHPUNIT_SUITE" == "integration" ]; then
              php bin/console doctrine:mongodb:schema:update
          fi && \
          if [ "$PHPUNIT_SUITE" == "unit" ]; then
            COVERAGE=" --coverage-clover=coverage.clover "
          fi && \
          vendor/bin/phpunit $COVERAGE --testsuite=$PHPUNIT_SUITE && \
          if [ $COVERAGE ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
          fi
      fi
  - >
      if [ "$COMPOSER_CHECK" = "true" ]; then
          composer check;
      fi
