imports:
    - { resource: security.yml }
    - { resource: config.yml }

# sentry is active on prod
sentry:
    dsn: "%graviton.sentry.dsn%"
    options:
        excluded_exceptions: "%graviton.sentry.dontReport%"
        environment: "%kernel.environment%"
        tags:
            application: graviton

monolog:
    handlers:
        main:
            type: "stream"
            path: "%graviton.log.path%"
            level: "%graviton.log.level%"
            channels: ["!event"]
            formatter: "log_formatter"
